name: tokenizer
description: Mostafa Fahimi base project which contains tools for starting a new project
version: 1.1.1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.7.2

flutter:
  uses-material-design: true
